config/routes.rb
Rails.application.routes.draw do
  resources :puppies do 
    resources :suggestions
  end

   root 'puppies#index'

end

app/models/puppy.rb
class Puppy < ActiveRecord::Base
	has_many :suggestions #A puppy has many suggestions

	#will validate that something is putdown for owner
	#meta-programming -> call this method and automatically generates code to run this in your class definition
	validates :owner, presence: true
	#validates(:owner, {presence => true})
end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
	belongs_to :puppy
	validates :name, presence: true
	validates :puppy, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
	#responders gem
	respond_to :html
	before_action :find_puppy, except: [:index, :new, :create]

	def index
		@puppies = Puppy.all
		respond_with @puppies
	end

	def show
		#puppy.find loads puppy of a particular id
		respond_with @puppy
	end

	def create
		@puppy = Puppy.create(puppy_params)
		respond_with @puppy
	end

	def new
		@puppy = Puppy.new
	end

	def edit
		respond_with @puppy
	end

	def update
		@puppy.update(puppy_params)
		respond_with @puppy
	end

	def destroy
		@puppy = Puppy.find(params[:id])
		@puppy.destroy
		respond_with @puppy
	end

	private
	def puppy_params
		params.require(:puppy).permit(:owner, :description, :color)
	end

	def find_puppy
		@puppy = Puppy.find(params[:id])
	end

end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
	respond_to :html
	before_action :find_puppy

	def create
		@suggestion = @puppy.suggestions.create(suggestion_params)

		respond_with @suggestion, location: puppy_url(@puppy)
	end

	private
	def suggestion_params
		params.require(:suggestion).permit(:name)
	end

	def find_puppy
		@puppy = Puppy.find(params[:puppy_id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/puppies_helper.rb
module PuppiesHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Corgi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/puppies/_form.html.erb
<% unless @puppy.errors.empty? %>
	<h2>Errors</h2>
	<ul>
		<% @puppy.errors.full_messages.each do |error| %>
			<li><%= error %></li>
		<%end%>
	</ul>
<%end%>
<!-- form_for finds the URL that it needs to post to! --> 
<%= form_for @puppy do |f| %>
	<p>Owner name: <%= f.text_field :owner %></p>
	<p>Color: <%= f.text_field :color %></p>
	<p>Description</p>
	<%= f.text_area :description %>
	<p><%= f.submit %></p>
<%end%>

app/views/puppies/edit.html.erb
<h1>Edit puppy </h1>

<%= render partial: 'form'%>

app/views/puppies/index.html.erb
<h1>Puppies</h1>
<ul>
	<% @puppies.each do |puppy| %>
		<li>
			Owned by: <%= puppy.owner %>,
			<% if puppy.color? %>
				color: <%= puppy.color %>
			<% end %>
			<%= link_to "More Info", puppy_url(puppy) %>
		</li>
	<% end %>
</ul>

<p><%=link_to "Add a new puppy", new_puppy_url %></p>

app/views/puppies/new.html.erb
<h1>Add a new puppy </h1>

<%= render partial: 'form' %>

app/views/puppies/show.html.erb
<p><%= link_to "Home", puppies_url() %></p>

<h1>Puppy owned by <%= @puppy.owner %></h1>
<p>Color: <%= @puppy.color %></p>
<p>Description: <%= @puppy.description %></p>

<h2>Suggestions </h2>
<ul>
	<% @puppy.suggestions.each do |suggestion| %>
		<li><%= suggestion.name %></li>
	<% end %>
</ul>

<%= form_for [@puppy, @puppy.suggestions.build] do |f| %>
	<p>Suggestion: <%= f.text_field :name, required: true %></p>
	<%= f.submit %> 
<%end%>

<p><%= link_to "Edit", edit_puppy_url(@puppy) %></p>